

import { Brand, CarModel, CarType, PowerType } from './types';

// Helper to generate placeholder images with text
const getPlaceHolder = (text: string) => `https://placehold.co/600x400/e2e8f0/1e293b?text=${encodeURIComponent(text)}`;

export const BRAND_LOGOS: Record<string, string> = {
    // ... logos are managed via text now, but keeping structure for compatibility
};

export const CAR_DATABASE: CarModel[] = [
  // --- XIAOMI ---
  {
    id: 'xiaomi_su7',
    brand: Brand.XIAOMI,
    name: '小米 SU7',
    priceRange: [21.59, 29.99],
    range: 830,
    sales: 18500,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['人车家全生态', '2.78秒破百', '高压快充', '防晒隔热'],
    imageUrl: getPlaceHolder('Xiaomi SU7'),
    acceleration: 2.78,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'xiaomi_yu7',
    brand: Brand.XIAOMI,
    name: '小米 YU7',
    priceRange: [23.99, 32.99],
    range: 750,
    sales: 12000,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['小米SUV', '超大空间', '家庭旗舰'],
    imageUrl: getPlaceHolder('Xiaomi YU7'),
    acceleration: 3.2,
    autonomousLevel: 'City NOA'
  },
  
  // --- TESLA ---
  {
    id: 'tesla_model3',
    brand: Brand.TESLA,
    name: 'Model 3 焕新版',
    priceRange: [23.19, 33.59],
    range: 713,
    sales: 15600,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['极致操控', '屏幕换挡', 'FSD能力', '极简内饰'],
    imageUrl: getPlaceHolder('Tesla Model 3'),
    acceleration: 4.4,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'tesla_modely',
    brand: Brand.TESLA,
    name: 'Model Y',
    priceRange: [24.99, 35.49],
    range: 688,
    sales: 42000,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['全球销量冠军', '空间利用率高', '保值率高'],
    imageUrl: getPlaceHolder('Tesla Model Y'),
    acceleration: 5.0,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'tesla_models',
    brand: Brand.TESLA,
    name: 'Model S',
    priceRange: [69.89, 81.49],
    range: 715,
    sales: 300,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['Plaid模式', '2.1秒破百', 'Yoke方向盘', '旗舰轿跑'],
    imageUrl: getPlaceHolder('Tesla Model S'),
    acceleration: 2.1,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'tesla_modelx',
    brand: Brand.TESLA,
    name: 'Model X',
    priceRange: [72.49, 82.49],
    range: 700,
    sales: 450,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['鹰翼门', '全景挡风', '六座布局'],
    imageUrl: getPlaceHolder('Tesla Model X'),
    acceleration: 2.6,
    autonomousLevel: 'City NOA'
  },

  // --- BYD SERIES ---
  {
    id: 'byd_seagull',
    brand: Brand.BYD,
    name: '海鸥',
    priceRange: [6.98, 8.58],
    range: 405,
    sales: 38000,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['代步神器', 'e平台3.0', '高安全'],
    imageUrl: getPlaceHolder('BYD Seagull'),
    acceleration: 13.0,
    autonomousLevel: 'L2'
  },
  {
    id: 'byd_dolphin',
    brand: Brand.BYD,
    name: '海豚',
    priceRange: [9.98, 12.98],
    range: 420,
    sales: 12000,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['精致代步', '热泵空调', '空间越级'],
    imageUrl: getPlaceHolder('BYD Dolphin'),
    acceleration: 10.5,
    autonomousLevel: 'L2'
  },
  {
    id: 'byd_e2',
    brand: Brand.BYD,
    name: '比亚迪 e2',
    priceRange: [8.98, 10.28],
    range: 405,
    sales: 2000,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['两厢跨界', '主要面向网约', '皮实耐用'],
    imageUrl: getPlaceHolder('BYD e2'),
    acceleration: 10.0,
    autonomousLevel: 'L2'
  },
  {
    id: 'byd_qin_plus_dmi',
    brand: Brand.BYD,
    name: '秦 PLUS DM-i',
    priceRange: [7.98, 12.58],
    range: 1245,
    sales: 26000,
    type: CarType.SEDAN,
    power: PowerType.PHEV,
    features: ['销量王者', '油电同价', '极致省油'],
    imageUrl: getPlaceHolder('Qin PLUS DM-i'),
    acceleration: 7.3,
    autonomousLevel: 'L2'
  },
  {
    id: 'byd_qin_plus_ev',
    brand: Brand.BYD,
    name: '秦 PLUS EV',
    priceRange: [10.98, 13.98],
    range: 510,
    sales: 8500,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['纯电轿车', '刀片电池', '网约车首选'],
    imageUrl: getPlaceHolder('Qin PLUS EV'),
    acceleration: 5.5, 
    autonomousLevel: 'L2'
  },
  {
    id: 'byd_qin_l',
    brand: Brand.BYD,
    name: '秦 L DM-i',
    priceRange: [9.98, 13.98],
    range: 2100,
    sales: 32000,
    type: CarType.SEDAN,
    power: PowerType.PHEV,
    features: ['第五代DM技术', '2.9L亏电油耗', '中级车尺寸'],
    imageUrl: getPlaceHolder('BYD Qin L'),
    acceleration: 7.5,
    autonomousLevel: 'L2'
  },
  {
    id: 'byd_destroyer_05',
    brand: Brand.BYD,
    name: '驱逐舰 05',
    priceRange: [7.98, 12.88],
    range: 1245,
    sales: 5000,
    type: CarType.SEDAN,
    power: PowerType.PHEV,
    features: ['海洋网秦PLUS', '年轻设计', 'DM-i混动'],
    imageUrl: getPlaceHolder('Destroyer 05'),
    acceleration: 7.3,
    autonomousLevel: 'L2'
  },
  {
    id: 'byd_seal_06_dmi',
    brand: Brand.BYD,
    name: '海豹 06 DM-i',
    priceRange: [9.98, 13.98],
    range: 2100,
    sales: 28000,
    type: CarType.SEDAN,
    power: PowerType.PHEV,
    features: ['第五代DM技术', '海洋美学', '超长续航'],
    imageUrl: getPlaceHolder('Seal 06 DM-i'),
    acceleration: 7.5,
    autonomousLevel: 'L2'
  },
  {
    id: 'byd_seal_ev',
    brand: Brand.BYD,
    name: '海豹 EV',
    priceRange: [17.98, 24.98],
    range: 700,
    sales: 3500,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['CTB技术', 'iTAC智能扭矩', '运动轿跑'],
    imageUrl: getPlaceHolder('BYD Seal EV'),
    acceleration: 3.8,
    autonomousLevel: 'L2+'
  },
  {
    id: 'byd_seal_dmi',
    brand: Brand.BYD,
    name: '海豹 DM-i',
    priceRange: [14.98, 21.98],
    range: 1300,
    sales: 4200,
    type: CarType.SEDAN,
    power: PowerType.PHEV,
    features: ['B+级尺寸', '豪华内饰', '舒适悬架'],
    imageUrl: getPlaceHolder('Seal DM-i'),
    acceleration: 7.9,
    autonomousLevel: 'L2'
  },
  {
    id: 'byd_seal_07_dmi',
    brand: Brand.BYD,
    name: '海豹 07 DM-i',
    priceRange: [13.98, 19.58],
    range: 1300,
    sales: 4000,
    type: CarType.SEDAN,
    power: PowerType.PHEV,
    features: ['行政B级车', '舒适底盘', '高阶配置'],
    imageUrl: getPlaceHolder('Seal 07 DM-i'),
    acceleration: 6.9,
    autonomousLevel: 'L2'
  },
  {
    id: 'byd_seal_06_gt',
    brand: Brand.BYD,
    name: '海豹 06 GT',
    priceRange: [13.68, 18.68],
    range: 605,
    sales: 2800,
    type: CarType.COUPE,
    power: PowerType.BEV,
    features: ['两厢钢炮', '后驱/四驱', '年轻运动'],
    imageUrl: getPlaceHolder('Seal 06 GT'),
    acceleration: 4.9,
    autonomousLevel: 'L2'
  },
  {
    id: 'byd_han_dmi',
    brand: Brand.BYD,
    name: '汉 DM-i',
    priceRange: [16.98, 22.58],
    range: 1260,
    sales: 11000,
    type: CarType.SEDAN,
    power: PowerType.PHEV,
    features: ['行政级空间', '成熟稳重', '省油舒适'],
    imageUrl: getPlaceHolder('BYD Han DM-i'),
    acceleration: 7.9,
    autonomousLevel: 'L2+'
  },
  {
    id: 'byd_han_ev',
    brand: Brand.BYD,
    name: '汉 EV',
    priceRange: [17.98, 24.98],
    range: 715,
    sales: 5000,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['纯电旗舰', '刀片电池', '创世版'],
    imageUrl: getPlaceHolder('BYD Han EV'),
    acceleration: 3.9,
    autonomousLevel: 'L2+'
  },
  {
    id: 'byd_tang',
    brand: Brand.BYD,
    name: '唐 DM-i',
    priceRange: [17.98, 21.98],
    range: 1100,
    sales: 9500,
    type: CarType.SUV,
    power: PowerType.PHEV,
    features: ['大七座SUV', 'FSD悬架', '适合二胎家庭'],
    imageUrl: getPlaceHolder('BYD Tang'),
    acceleration: 8.5,
    autonomousLevel: 'L2'
  },
  {
    id: 'byd_song_pro_dmi',
    brand: Brand.BYD,
    name: '宋 Pro DM-i',
    priceRange: [10.98, 13.98],
    range: 1090,
    sales: 21000,
    type: CarType.SUV,
    power: PowerType.PHEV,
    features: ['家用入门SUV', '性价比极高', '第五代DM(新款)'],
    imageUrl: getPlaceHolder('Song Pro DM-i'),
    acceleration: 7.9,
    autonomousLevel: 'L2'
  },
  {
    id: 'byd_song_plus_dmi',
    brand: Brand.BYD,
    name: '宋 PLUS DM-i',
    priceRange: [12.98, 16.98],
    range: 1250,
    sales: 29000,
    type: CarType.SUV,
    power: PowerType.PHEV,
    features: ['国民SUV', '保有量极大', '舒适家用'],
    imageUrl: getPlaceHolder('Song PLUS DM-i'),
    acceleration: 7.9,
    autonomousLevel: 'L2'
  },
   {
    id: 'byd_song_plus_ev',
    brand: Brand.BYD,
    name: '宋 PLUS EV',
    priceRange: [14.98, 18.98],
    range: 605,
    sales: 7500,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['纯电家用SUV', '出口爆款', '宽体设计'],
    imageUrl: getPlaceHolder('Song PLUS EV'),
    acceleration: 8.0,
    autonomousLevel: 'L2'
  },
  {
    id: 'byd_song_l_dmi',
    brand: Brand.BYD,
    name: '宋 L DM-i',
    priceRange: [13.58, 17.58],
    range: 1500,
    sales: 18000,
    type: CarType.SUV,
    power: PowerType.PHEV,
    features: ['王朝网中级SUV', '第五代DM', '大空间'],
    imageUrl: getPlaceHolder('Song L DM-i'),
    acceleration: 7.7,
    autonomousLevel: 'L2'
  },
  {
    id: 'byd_song_l_ev',
    brand: Brand.BYD,
    name: '宋 L EV',
    priceRange: [18.98, 24.98],
    range: 662,
    sales: 4500,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['最美比亚迪', '猎装SUV', '云辇-C'],
    imageUrl: getPlaceHolder('BYD Song L'),
    acceleration: 4.3,
    autonomousLevel: 'High-Speed NOA'
  },
  {
    id: 'byd_yuan_plus',
    brand: Brand.BYD,
    name: '元 PLUS',
    priceRange: [11.98, 14.78],
    range: 510,
    sales: 25000,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['潮跑SUV', 'e平台3.0', '海外Atto 3'],
    imageUrl: getPlaceHolder('BYD Yuan Plus'),
    acceleration: 7.3,
    autonomousLevel: 'L2'
  },
  {
    id: 'byd_yuan_up',
    brand: Brand.BYD,
    name: '元 UP',
    priceRange: [9.68, 11.98],
    range: 401,
    sales: 11000,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['小型SUV', 'CTB技术', '年轻时尚'],
    imageUrl: getPlaceHolder('BYD Yuan UP'),
    acceleration: 12.0,
    autonomousLevel: 'L2'
  },
  {
    id: 'byd_yuan_pro',
    brand: Brand.BYD,
    name: '元 Pro',
    priceRange: [9.58, 11.38],
    range: 401,
    sales: 3000,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['小背包', '城市代步', '高坐姿'],
    imageUrl: getPlaceHolder('BYD Yuan Pro'),
    acceleration: 12.0,
    autonomousLevel: 'L2'
  },
  {
    id: 'byd_sealion_07',
    brand: Brand.BYD,
    name: '海狮 07 EV',
    priceRange: [18.98, 23.98],
    range: 610,
    sales: 6500,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['e平台3.0 Evo', '天神之眼智驾', '快充升级'],
    imageUrl: getPlaceHolder('Sea Lion 07'),
    acceleration: 4.2,
    autonomousLevel: 'High-Speed NOA'
  },
  {
    id: 'byd_frigate_07',
    brand: Brand.BYD,
    name: '护卫舰 07',
    priceRange: [17.98, 25.98],
    range: 1200,
    sales: 1500,
    type: CarType.SUV,
    power: PowerType.PHEV,
    features: ['大五座SUV', '海洋网旗舰', '舒适大空间'],
    imageUrl: getPlaceHolder('Frigate 07'),
    acceleration: 4.7,
    autonomousLevel: 'L2'
  },
   {
    id: 'byd_xia',
    brand: Brand.BYD,
    name: '夏',
    priceRange: [28.98, 35.98],
    range: 1000,
    sales: 5000,
    type: CarType.MPV,
    power: PowerType.PHEV,
    features: ['王朝旗舰MPV', '第五代DM', '云辇-C'],
    imageUrl: getPlaceHolder('BYD Xia'),
    acceleration: 6.5,
    autonomousLevel: 'L2+'
  },

  // --- FANG CHENG BAO ---
  {
    id: 'fcb_bao5',
    brand: Brand.FANGCHENGBAO,
    name: '方程豹 豹5',
    priceRange: [23.98, 30.28],
    range: 1200,
    sales: 4500,
    type: CarType.OFFROAD,
    power: PowerType.PHEV,
    features: ['DMO超混越野', '云辇-P', '硬派造型'],
    imageUrl: getPlaceHolder('Bao 5'),
    acceleration: 4.8,
    autonomousLevel: 'L2+'
  },
  {
    id: 'fcb_bao8',
    brand: Brand.FANGCHENGBAO,
    name: '方程豹 豹8',
    priceRange: [37.98, 40.78],
    range: 1200,
    sales: 2000,
    type: CarType.OFFROAD,
    power: PowerType.PHEV,
    features: ['华为乾昆智驾', '三排座', '旗舰越野'],
    imageUrl: getPlaceHolder('Bao 8'),
    acceleration: 4.8,
    autonomousLevel: 'City NOA'
  },

  // --- HIMA (Huawei) ---
  {
    id: 'aito_m7',
    brand: Brand.AITO,
    name: '问界 M7',
    priceRange: [24.98, 32.98],
    range: 1300,
    sales: 16000,
    type: CarType.SUV,
    power: PowerType.REEV,
    features: ['ADS 3.0', '鸿蒙座舱', '零重力座椅'],
    imageUrl: getPlaceHolder('AITO M7'),
    acceleration: 4.8,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'aito_m9',
    brand: Brand.AITO,
    name: '问界 M9',
    priceRange: [46.98, 56.98],
    range: 1402,
    sales: 15500,
    type: CarType.SUV,
    power: PowerType.REEV,
    features: ['智慧大灯', '途灵底盘', '隐私声盾'],
    imageUrl: getPlaceHolder('AITO M9'),
    acceleration: 4.9,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'aito_m5',
    brand: Brand.AITO,
    name: '问界 M5',
    priceRange: [24.98, 27.98],
    range: 1250,
    sales: 4500,
    type: CarType.SUV,
    power: PowerType.REEV,
    features: ['全铝底盘', '操控好', '华为智驾'],
    imageUrl: getPlaceHolder('AITO M5'),
    acceleration: 4.4,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'luxeed_s7',
    brand: Brand.LUXEED,
    name: '智界 S7',
    priceRange: [24.98, 34.98],
    range: 855,
    sales: 3500,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['大空间轿车', '途灵底盘', '800V'],
    imageUrl: getPlaceHolder('Luxeed S7'),
    acceleration: 3.3,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'luxeed_r7',
    brand: Brand.LUXEED,
    name: '智界 R7',
    priceRange: [25.98, 33.98],
    range: 802,
    sales: 6000,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['轿跑SUV', '超大后排', '华为智驾'],
    imageUrl: getPlaceHolder('Luxeed R7'),
    acceleration: 3.9,
    autonomousLevel: 'City NOA'
  },
   {
    id: 'stelato_s9',
    brand: Brand.STELATO,
    name: '享界 S9',
    priceRange: [39.98, 44.98],
    range: 816,
    sales: 2200,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['行政旗舰', '后排零重力', '华为ADS 3.0'],
    imageUrl: getPlaceHolder('Stelato S9'),
    acceleration: 3.9,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'maextro_s800',
    brand: Brand.MAEXTRO,
    name: '尊界 S800',
    priceRange: [100, 150],
    range: 750,
    sales: 200,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['百万级豪车', '极致奢华', '华为顶尖科技'],
    imageUrl: getPlaceHolder('Maextro S800'),
    acceleration: 3.5,
    autonomousLevel: 'City NOA'
  },

  // --- NIO ---
  {
    id: 'nio_et5',
    brand: Brand.NIO,
    name: '蔚来 ET5',
    priceRange: [29.80, 35.60],
    range: 710,
    sales: 4500,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['换电', '轿跑设计', '双电机'],
    imageUrl: getPlaceHolder('NIO ET5'),
    acceleration: 4.0,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'nio_et5t',
    brand: Brand.NIO,
    name: '蔚来 ET5T',
    priceRange: [29.80, 35.60],
    range: 710,
    sales: 5500,
    type: CarType.WAGON,
    power: PowerType.BEV,
    features: ['换电', '最美旅行车', '双电机标配'],
    imageUrl: getPlaceHolder('NIO ET5T'),
    acceleration: 4.0,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'nio_es6',
    brand: Brand.NIO,
    name: '蔚来 ES6',
    priceRange: [33.80, 39.60],
    range: 625,
    sales: 7800,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['换电服务', '女王副驾', 'NOP+智驾'],
    imageUrl: getPlaceHolder('NIO ES6'),
    acceleration: 4.5,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'nio_ec6',
    brand: Brand.NIO,
    name: '蔚来 EC6',
    priceRange: [35.80, 41.60],
    range: 630,
    sales: 2500,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['轿跑SUV', '电动尾翼', '优雅设计'],
    imageUrl: getPlaceHolder('NIO EC6'),
    acceleration: 4.4,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'nio_ec7',
    brand: Brand.NIO,
    name: '蔚来 EC7',
    priceRange: [45.80, 54.80],
    range: 635,
    sales: 800,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['旗舰轿跑SUV', '最快蔚来', '主动升降尾翼'],
    imageUrl: getPlaceHolder('NIO EC7'),
    acceleration: 3.8,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'nio_et7',
    brand: Brand.NIO,
    name: '蔚来 ET7',
    priceRange: [42.80, 51.60],
    range: 1050, 
    sales: 1200,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['行政旗舰', '后排行政屏', '空气悬架'],
    imageUrl: getPlaceHolder('NIO ET7'),
    acceleration: 3.8,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'nio_es8',
    brand: Brand.NIO,
    name: '蔚来 ES8',
    priceRange: [49.80, 59.80],
    range: 605,
    sales: 2100,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['全场景旗舰SUV', '双腔空悬', '行政六座'],
    imageUrl: getPlaceHolder('NIO ES8'),
    acceleration: 4.1,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'nio_et9',
    brand: Brand.NIO,
    name: '蔚来 ET9',
    priceRange: [80, 80],
    range: 800,
    sales: 100,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['行政旗舰', '900V', '天行底盘'],
    imageUrl: getPlaceHolder('NIO ET9'),
    acceleration: 3.5,
    autonomousLevel: 'City NOA'
  },

  // --- ONVO ---
  {
    id: 'onvo_l60',
    brand: Brand.ONVO,
    name: '乐道 L60',
    priceRange: [20.69, 23.59],
    range: 730,
    sales: 8500,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['换电', '家庭大空间', '超低能耗'],
    imageUrl: getPlaceHolder('Onvo L60'),
    acceleration: 4.6,
    autonomousLevel: 'High-Speed NOA'
  },
  {
    id: 'onvo_l90',
    brand: Brand.ONVO,
    name: '乐道 L90',
    priceRange: [30, 40],
    range: 800,
    sales: 2000,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['旗舰轿车', '换电', '超大空间'],
    imageUrl: getPlaceHolder('Onvo L90'),
    acceleration: 4.0,
    autonomousLevel: 'High-Speed NOA'
  },

  // --- LI AUTO ---
  {
    id: 'li_l6',
    brand: Brand.LIXIANG,
    name: '理想 L6',
    priceRange: [24.98, 27.98],
    range: 1390,
    sales: 22000,
    type: CarType.SUV,
    power: PowerType.REEV,
    features: ['小号L7', '全系四驱', '家庭首选'],
    imageUrl: getPlaceHolder('Li Auto L6'),
    acceleration: 5.4,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'li_l7',
    brand: Brand.LIXIANG,
    name: '理想 L7',
    priceRange: [30.18, 35.98],
    range: 1360,
    sales: 11000,
    type: CarType.SUV,
    power: PowerType.REEV,
    features: ['大五座SUV', '皇后座', '魔毯空气悬架'],
    imageUrl: getPlaceHolder('Li Auto L7'),
    acceleration: 5.3,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'li_l8',
    brand: Brand.LIXIANG,
    name: '理想 L8',
    priceRange: [32.18, 37.98],
    range: 1360,
    sales: 6500,
    type: CarType.SUV,
    power: PowerType.REEV,
    features: ['家庭六座', '二排娱乐屏', '舒适平权'],
    imageUrl: getPlaceHolder('Li Auto L8'),
    acceleration: 5.3,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'li_l9',
    brand: Brand.LIXIANG,
    name: '理想 L9',
    priceRange: [40.98, 43.98],
    range: 1412,
    sales: 7800,
    type: CarType.SUV,
    power: PowerType.REEV,
    features: ['全尺寸SUV', '旗舰舒适', '冷暖冰箱'],
    imageUrl: getPlaceHolder('Li Auto L9'),
    acceleration: 5.3,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'li_mega',
    brand: Brand.LIXIANG,
    name: '理想 MEGA',
    priceRange: [52.98, 52.98],
    range: 710,
    sales: 1200,
    type: CarType.MPV,
    power: PowerType.BEV,
    features: ['公路高铁', '5C超充', '极致风阻'],
    imageUrl: getPlaceHolder('Li Auto MEGA'),
    acceleration: 5.5,
    autonomousLevel: 'City NOA'
  },

  // --- XPENG ---
  {
    id: 'xpeng_mona_m03',
    brand: Brand.XPENG,
    name: '小鹏 MONA M03',
    priceRange: [11.98, 15.58],
    range: 620,
    sales: 12500,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['极致掀背', '极具性价比', '超大后备箱'],
    imageUrl: getPlaceHolder('XPeng MONA M03'),
    acceleration: 7.4,
    autonomousLevel: 'High-Speed NOA'
  },
  {
    id: 'xpeng_p5',
    brand: Brand.XPENG,
    name: '小鹏 P5',
    priceRange: [15.69, 17.49],
    range: 500,
    sales: 1000,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['百变空间', '前排全平', '家轿'],
    imageUrl: getPlaceHolder('XPeng P5'),
    acceleration: 7.5,
    autonomousLevel: 'L2+'
  },
  {
    id: 'xpeng_p7i',
    brand: Brand.XPENG,
    name: '小鹏 P7i',
    priceRange: [22.39, 33.99],
    range: 702,
    sales: 3000,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['经典轿跑', '操控升级', 'XNGP'],
    imageUrl: getPlaceHolder('XPeng P7i'),
    acceleration: 3.9,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'xpeng_p7_plus',
    brand: Brand.XPENG,
    name: '小鹏 P7+',
    priceRange: [18.68, 21.88],
    range: 710,
    sales: 8000,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['AI汽车', '视觉智驾', '大空间'],
    imageUrl: getPlaceHolder('XPeng P7+'),
    acceleration: 5.9,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'xpeng_g6',
    brand: Brand.XPENG,
    name: '小鹏 G6',
    priceRange: [19.99, 27.69],
    range: 755,
    sales: 6500,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['XNGP智驾', '800V快充', '空间魔术师'],
    imageUrl: getPlaceHolder('XPeng G6'),
    acceleration: 3.9,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'xpeng_g9',
    brand: Brand.XPENG,
    name: '小鹏 G9',
    priceRange: [26.39, 35.99],
    range: 702,
    sales: 3500,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['5D音乐座舱', '超快充', '旗舰SUV'],
    imageUrl: getPlaceHolder('XPeng G9'),
    acceleration: 3.9,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'xpeng_x9',
    brand: Brand.XPENG,
    name: '小鹏 X9',
    priceRange: [35.98, 41.98],
    range: 702,
    sales: 2200,
    type: CarType.MPV,
    power: PowerType.BEV,
    features: ['后轮转向', '魔术空间', '年轻化MPV'],
    imageUrl: getPlaceHolder('XPeng X9'),
    acceleration: 5.7,
    autonomousLevel: 'City NOA'
  },

  // --- ZEEKR ---
  {
    id: 'zeekr_001',
    brand: Brand.ZEEKR,
    name: '极氪 001',
    priceRange: [25.90, 32.90],
    range: 750,
    sales: 9000,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['猎装造型', '极致底盘', '雅马哈音响'],
    imageUrl: getPlaceHolder('Zeekr 001'),
    acceleration: 3.3,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'zeekr_007',
    brand: Brand.ZEEKR,
    name: '极氪 007',
    priceRange: [20.99, 29.99],
    range: 870,
    sales: 6000,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['800V全栈', '灯幕交互', '极高性价比'],
    imageUrl: getPlaceHolder('Zeekr 007'),
    acceleration: 2.84,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'zeekr_7x',
    brand: Brand.ZEEKR,
    name: '极氪 7X',
    priceRange: [22.99, 26.99],
    range: 780,
    sales: 10500,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['家用大五座', '极氪操控', '800V'],
    imageUrl: getPlaceHolder('Zeekr 7X'),
    acceleration: 3.8,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'zeekr_x',
    brand: Brand.ZEEKR,
    name: '极氪 X',
    priceRange: [20.00, 22.00],
    range: 560,
    sales: 1500,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['轻奢紧凑SUV', '百变中岛', '设计感强'],
    imageUrl: getPlaceHolder('Zeekr X'),
    acceleration: 3.7,
    autonomousLevel: 'L2+'
  },
  {
    id: 'zeekr_mix',
    brand: Brand.ZEEKR,
    name: '极氪 MIX',
    priceRange: [27.99, 29.99],
    range: 702,
    sales: 1200,
    type: CarType.MPV,
    power: PowerType.BEV,
    features: ['宝宝巴士', '对开滑门', '旋转座椅'],
    imageUrl: getPlaceHolder('Zeekr MIX'),
    acceleration: 6.8,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'zeekr_009',
    brand: Brand.ZEEKR,
    name: '极氪 009',
    priceRange: [43.90, 78.90],
    range: 822,
    sales: 1800,
    type: CarType.MPV,
    power: PowerType.BEV,
    features: ['光之泉前脸', '豪华MPV', '最安全MPV'],
    imageUrl: getPlaceHolder('Zeekr 009'),
    acceleration: 4.5,
    autonomousLevel: 'High-Speed NOA'
  },

  // --- GEELY / GALAXY / GEOMETRY / SMART ---
  {
    id: 'galaxy_e5',
    brand: Brand.GALAXY,
    name: '吉利银河 E5',
    priceRange: [10.98, 14.58],
    range: 530,
    sales: 13000,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['神盾短刀电池', 'Flyme Auto', '全球车型'],
    imageUrl: getPlaceHolder('Galaxy E5'),
    acceleration: 6.9,
    autonomousLevel: 'L2'
  },
  {
    id: 'galaxy_e8',
    brand: Brand.GALAXY,
    name: '吉利银河 E8',
    priceRange: [16.58, 22.88],
    range: 665,
    sales: 4000,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['45寸8K大屏', '低风阻', '极佳操控'],
    imageUrl: getPlaceHolder('Galaxy E8'),
    acceleration: 3.49,
    autonomousLevel: 'High-Speed NOA'
  },
  {
    id: 'galaxy_l7',
    brand: Brand.GALAXY,
    name: '吉利银河 L7',
    priceRange: [12.57, 16.97],
    range: 1370,
    sales: 6500,
    type: CarType.SUV,
    power: PowerType.PHEV,
    features: ['雷神电混', '三挡DHT', '宠爱副驾'],
    imageUrl: getPlaceHolder('Galaxy L7'),
    acceleration: 6.9,
    autonomousLevel: 'L2'
  },
  {
    id: 'galaxy_l6',
    brand: Brand.GALAXY,
    name: '吉利银河 L6',
    priceRange: [9.98, 12.28],
    range: 1370,
    sales: 3500,
    type: CarType.SEDAN,
    power: PowerType.PHEV,
    features: ['家轿性价比', '雷神动力', '舒适座舱'],
    imageUrl: getPlaceHolder('Galaxy L6'),
    acceleration: 6.5,
    autonomousLevel: 'L2'
  },
  {
    id: 'geely_star',
    brand: Brand.GEELY,
    name: '吉利星愿',
    priceRange: [6.98, 9.88],
    range: 410,
    sales: 8000,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['后驱', 'Flyme Auto', '精品小车'],
    imageUrl: getPlaceHolder('Geely Xingyuan'),
    acceleration: 9.8,
    autonomousLevel: 'L2'
  },
  {
    id: 'geely_panda',
    brand: Brand.GEELY,
    name: '吉利熊猫',
    priceRange: [2.99, 5.69],
    range: 200,
    sales: 11000,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['微型车', '快充', '可爱造型'],
    imageUrl: getPlaceHolder('Geely Panda'),
    acceleration: 15.0,
    autonomousLevel: 'L2'
  },
  {
    id: 'geometry_e',
    brand: Brand.GEOMETRY,
    name: '几何 E 萤火虫',
    priceRange: [5.98, 8.98],
    range: 401,
    sales: 4500,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['小SUV', '好开', '性价比'],
    imageUrl: getPlaceHolder('Geometry E'),
    acceleration: 12.0,
    autonomousLevel: 'L2'
  },
  {
    id: 'smart_1',
    brand: Brand.SMART,
    name: 'Smart 精灵#1',
    priceRange: [15.49, 28.49],
    range: 560,
    sales: 2500,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['奔驰设计', '吉利浩瀚平台', '都市时尚'],
    imageUrl: getPlaceHolder('Smart #1'),
    acceleration: 6.7,
    autonomousLevel: 'L2'
  },
  {
    id: 'smart_3',
    brand: Brand.SMART,
    name: 'Smart 精灵#3',
    priceRange: [16.49, 28.99],
    range: 580,
    sales: 1800,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['轿跑SUV', '运动操控', 'BRABUS版'],
    imageUrl: getPlaceHolder('Smart #3'),
    acceleration: 5.4,
    autonomousLevel: 'L2'
  },
  {
    id: 'smart_5',
    brand: Brand.SMART,
    name: 'Smart 精灵#5',
    priceRange: [22.99, 26.99],
    range: 740,
    sales: 1000,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['大五座', '硬派越野风', '800V'],
    imageUrl: getPlaceHolder('Smart #5'),
    acceleration: 4.9,
    autonomousLevel: 'City NOA'
  },

  // --- LEAPMOTOR ---
  {
    id: 'leap_c10',
    brand: Brand.LEAPMOTOR,
    name: '零跑 C10',
    priceRange: [12.88, 16.88],
    range: 1190,
    sales: 8500,
    type: CarType.SUV,
    power: PowerType.REEV,
    features: ['更年轻', '8295芯片', '母婴级座舱'],
    imageUrl: getPlaceHolder('Leapmotor C10'),
    acceleration: 7.68,
    autonomousLevel: 'High-Speed NOA'
  },
  {
    id: 'leap_c16',
    brand: Brand.LEAPMOTOR,
    name: '零跑 C16',
    priceRange: [15.58, 18.58],
    range: 1095,
    sales: 9000,
    type: CarType.SUV,
    power: PowerType.REEV,
    features: ['六座SUV', '后排娱乐屏', '家庭性价比'],
    imageUrl: getPlaceHolder('Leapmotor C16'),
    acceleration: 8.4,
    autonomousLevel: 'High-Speed NOA'
  },
  {
    id: 'leap_c11',
    brand: Brand.LEAPMOTOR,
    name: '零跑 C11',
    priceRange: [14.88, 20.98],
    range: 1210,
    sales: 6000,
    type: CarType.SUV,
    power: PowerType.REEV,
    features: ['大五座', '无框车门', '前双叉臂'],
    imageUrl: getPlaceHolder('Leapmotor C11'),
    acceleration: 7.9,
    autonomousLevel: 'L2+'
  },
  {
    id: 'leap_c01',
    brand: Brand.LEAPMOTOR,
    name: '零跑 C01',
    priceRange: [13.68, 15.88],
    range: 1276,
    sales: 2500,
    type: CarType.SEDAN,
    power: PowerType.REEV,
    features: ['5米车长', '轿跑设计', '性价比之王'],
    imageUrl: getPlaceHolder('Leapmotor C01'),
    acceleration: 7.6,
    autonomousLevel: 'L2+'
  },
  {
    id: 'leap_t03',
    brand: Brand.LEAPMOTOR,
    name: '零跑 T03',
    priceRange: [4.99, 6.99],
    range: 403,
    sales: 5000,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['五门四座', '代步小车', '智能配置'],
    imageUrl: getPlaceHolder('Leapmotor T03'),
    acceleration: 12.0,
    autonomousLevel: 'L2'
  },

  // --- AVATR / DEEPAL / CHANGAN ---
  {
    id: 'avatr_11',
    brand: Brand.AVATR,
    name: '阿维塔 11',
    priceRange: [30.08, 39.08],
    range: 730,
    sales: 1500,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['情感智能', '独特设计', '华为三激光'],
    imageUrl: getPlaceHolder('Avatr 11'),
    acceleration: 3.98,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'avatr_12',
    brand: Brand.AVATR,
    name: '阿维塔 12',
    priceRange: [26.58, 37.88],
    range: 700,
    sales: 2000,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['电子外后视镜', '无后窗设计', '未来感'],
    imageUrl: getPlaceHolder('Avatr 12'),
    acceleration: 3.9,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'avatr_07',
    brand: Brand.AVATR,
    name: '阿维塔 07',
    priceRange: [21.99, 28.99],
    range: 1100,
    sales: 4500,
    type: CarType.SUV,
    power: PowerType.REEV,
    features: ['昆仑增程', '太行底盘', '都市豪华'],
    imageUrl: getPlaceHolder('Avatr 07'),
    acceleration: 4.9,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'deepal_sl03',
    brand: Brand.DEEPAL,
    name: '深蓝 SL03',
    priceRange: [11.99, 14.69],
    range: 1200,
    sales: 6000,
    type: CarType.SEDAN,
    power: PowerType.REEV,
    features: ['机甲风格', '向日葵屏', '无框车门'],
    imageUrl: getPlaceHolder('Deepal SL03'),
    acceleration: 5.9,
    autonomousLevel: 'L2+'
  },
  {
    id: 'deepal_s07',
    brand: Brand.DEEPAL,
    name: '深蓝 S07',
    priceRange: [14.99, 21.29],
    range: 1120,
    sales: 8500,
    type: CarType.SUV,
    power: PowerType.REEV,
    features: ['华为乾昆智驾', '零重力座椅', '全息投影'],
    imageUrl: getPlaceHolder('Deepal S07'),
    acceleration: 7.6,
    autonomousLevel: 'High-Speed NOA'
  },
  {
    id: 'deepal_s05',
    brand: Brand.DEEPAL,
    name: '深蓝 S05',
    priceRange: [11.99, 14.99],
    range: 510,
    sales: 5500,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['多彩车身', '年轻入门', '云台相机'],
    imageUrl: getPlaceHolder('Deepal S05'),
    acceleration: 7.5,
    autonomousLevel: 'L2'
  },
  {
    id: 'deepal_l07',
    brand: Brand.DEEPAL,
    name: '深蓝 L07',
    priceRange: [15.19, 17.39],
    range: 1330,
    sales: 3000,
    type: CarType.SEDAN,
    power: PowerType.REEV,
    features: ['舒适偏向', '华为智驾', '长续航'],
    imageUrl: getPlaceHolder('Deepal L07'),
    acceleration: 6.0,
    autonomousLevel: 'High-Speed NOA'
  },
  {
    id: 'changan_lumin',
    brand: Brand.CHANGAN,
    name: '长安 Lumin',
    priceRange: [3.79, 6.19],
    range: 301,
    sales: 11000,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['糯玉米', '可爱圆润', '宽敞微型车'],
    imageUrl: getPlaceHolder('Changan Lumin'),
    acceleration: 15.0,
    autonomousLevel: 'L2'
  },
  {
    id: 'changan_uniz',
    brand: Brand.CHANGAN,
    name: '长安 UNI-Z',
    priceRange: [11.79, 13.19],
    range: 1200,
    sales: 7000,
    type: CarType.SUV,
    power: PowerType.PHEV,
    features: ['蓝鲸智电iDD', '跃级空间', '智能座舱'],
    imageUrl: getPlaceHolder('Changan UNI-Z'),
    acceleration: 7.4,
    autonomousLevel: 'L2'
  },
  {
    id: 'changan_nevo_a07',
    brand: Brand.CHANGAN,
    name: '长安启源 A07',
    priceRange: [13.59, 17.99],
    range: 1200,
    sales: 4500,
    type: CarType.SEDAN,
    power: PowerType.REEV,
    features: ['数智座舱', '掀背设计', '行政级底盘'],
    imageUrl: getPlaceHolder('Nevo A07'),
    acceleration: 7.8,
    autonomousLevel: 'L2'
  },

  // --- GAC AION / HYPER / TRUMPCHI ---
  {
    id: 'aion_s_max',
    brand: Brand.GAC_AION,
    name: 'AION S MAX',
    priceRange: [14.99, 17.99],
    range: 610,
    sales: 7000,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['舒适家轿', '大空间', '长续航'],
    imageUrl: getPlaceHolder('AION S MAX'),
    acceleration: 7.5,
    autonomousLevel: 'L2'
  },
  {
    id: 'aion_rt',
    brand: Brand.GAC_AION,
    name: 'AION RT',
    priceRange: [11.98, 16.58],
    range: 650,
    sales: 5500,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['迅猛龙', '激光雷达', '高阶智驾'],
    imageUrl: getPlaceHolder('AION RT'),
    acceleration: 7.5,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'aion_y_plus',
    brand: Brand.GAC_AION,
    name: 'AION Y Plus',
    priceRange: [9.98, 14.58],
    range: 610,
    sales: 18000,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['变态大空间', '前排全平放倒', '露营神车'],
    imageUrl: getPlaceHolder('AION Y Plus'),
    acceleration: 8.5,
    autonomousLevel: 'L2'
  },
  {
    id: 'aion_v_2nd',
    brand: Brand.GAC_AION,
    name: '第二代 AION V',
    priceRange: [12.98, 18.98],
    range: 750,
    sales: 9000,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['霸王龙', '激光雷达', '硬派造型'],
    imageUrl: getPlaceHolder('AION V'),
    acceleration: 7.9,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'hyper_ht',
    brand: Brand.HYPER,
    name: '昊铂 HT',
    priceRange: [21.39, 32.99],
    range: 825,
    sales: 1200,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['鸥翼门', '豪华内饰', '超快充'],
    imageUrl: getPlaceHolder('Hyper HT'),
    acceleration: 5.8,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'hyper_gt',
    brand: Brand.HYPER,
    name: '昊铂 GT',
    priceRange: [20.39, 25.99],
    range: 710,
    sales: 500,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['旋翼门', '运动后驱', '七翼GT'],
    imageUrl: getPlaceHolder('Hyper GT'),
    acceleration: 4.9,
    autonomousLevel: 'High-Speed NOA'
  },
  {
    id: 'trumpchi_e8',
    brand: Brand.TRUMPCHI,
    name: '传祺 E8',
    priceRange: [20.98, 23.58],
    range: 1200,
    sales: 4500,
    type: CarType.MPV,
    power: PowerType.PHEV,
    features: ['家用MPV', '空间魔术', '舒适省油'],
    imageUrl: getPlaceHolder('Trumpchi E8'),
    acceleration: 8.8,
    autonomousLevel: 'L2'
  },
  {
    id: 'trumpchi_e9',
    brand: Brand.TRUMPCHI,
    name: '传祺 E9',
    priceRange: [31.98, 40.98],
    range: 1032,
    sales: 2000,
    type: CarType.MPV,
    power: PowerType.PHEV,
    features: ['商务旗舰', '醒狮前脸', '豪华座舱'],
    imageUrl: getPlaceHolder('Trumpchi E9'),
    acceleration: 8.8,
    autonomousLevel: 'L2+'
  },
  
  // --- IM (智己) ---
  {
    id: 'im_ls6',
    brand: Brand.IM,
    name: '智己 LS6',
    priceRange: [21.69, 27.99],
    range: 760,
    sales: 6500,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['准900V平台', '全系激光雷达', '数字底盘'],
    imageUrl: getPlaceHolder('IM LS6'),
    acceleration: 3.48,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'im_ls7',
    brand: Brand.IM,
    name: '智己 LS7',
    priceRange: [28.98, 45.98],
    range: 660,
    sales: 1200,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['零重力座椅', '半幅方向盘', '超大视野'],
    imageUrl: getPlaceHolder('IM LS7'),
    acceleration: 4.5,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'im_l6',
    brand: Brand.IM,
    name: '智己 L6',
    priceRange: [21.99, 34.59],
    range: 850,
    sales: 3500,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['灵蜥数字底盘', '蟹行模式', '超强操控'],
    imageUrl: getPlaceHolder('IM L6'),
    acceleration: 2.74,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'im_l7',
    brand: Brand.IM,
    name: '智己 L7',
    priceRange: [29.99, 41.98],
    range: 708,
    sales: 500,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['驾控旗舰', '四轮转向', '流线造型'],
    imageUrl: getPlaceHolder('IM L7'),
    acceleration: 3.87,
    autonomousLevel: 'City NOA'
  },

   // --- DENZA ---
  {
    id: 'denza_d9',
    brand: Brand.DENZA,
    name: '腾势 D9',
    priceRange: [33.98, 60.06],
    range: 1040,
    sales: 8500,
    type: CarType.MPV,
    power: PowerType.PHEV,
    features: ['销量之王', '宜商宜家', 'DM-i超级混动'],
    imageUrl: getPlaceHolder('Denza D9'),
    acceleration: 7.9,
    autonomousLevel: 'L2+'
  },
  {
    id: 'denza_n7',
    brand: Brand.DENZA,
    name: '腾势 N7',
    priceRange: [23.98, 32.98],
    range: 702,
    sales: 1500,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['猎跑SUV', '云辇-A', '双枪快充'],
    imageUrl: getPlaceHolder('Denza N7'),
    acceleration: 3.9,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'denza_n8',
    brand: Brand.DENZA,
    name: '腾势 N8',
    priceRange: [31.98, 32.68],
    range: 1030,
    sales: 600,
    type: CarType.SUV,
    power: PowerType.PHEV,
    features: ['中大型SUV', '越野能力', '豪华配置'],
    imageUrl: getPlaceHolder('Denza N8'),
    acceleration: 4.3,
    autonomousLevel: 'L2+'
  },
  {
    id: 'denza_z9gt',
    brand: Brand.DENZA,
    name: '腾势 Z9GT',
    priceRange: [33.48, 41.48],
    range: 1100,
    sales: 3500,
    type: CarType.WAGON,
    power: PowerType.PHEV,
    features: ['易三方', '双枪快充', '猎装轿跑'],
    imageUrl: getPlaceHolder('Denza Z9GT'),
    acceleration: 3.6,
    autonomousLevel: 'City NOA'
  },

  // --- TANK / WEY / ORA / HAVAL (GWM) ---
  {
    id: 'tank_300',
    brand: Brand.TANK,
    name: '坦克 300 Hi4-T',
    priceRange: [26.98, 26.98],
    range: 860,
    sales: 6500,
    type: CarType.OFFROAD,
    power: PowerType.PHEV,
    features: ['经典方盒子', '越野标杆', '插混更省油'],
    imageUrl: getPlaceHolder('Tank 300 Hi4-T'),
    acceleration: 8.1,
    autonomousLevel: 'L2'
  },
  {
    id: 'tank_400',
    brand: Brand.TANK,
    name: '坦克 400 Hi4-T',
    priceRange: [28.58, 28.98],
    range: 800,
    sales: 3500,
    type: CarType.OFFROAD,
    power: PowerType.PHEV,
    features: ['机甲风格', '硬派越野', '豪华内饰'],
    imageUrl: getPlaceHolder('Tank 400 Hi4-T'),
    acceleration: 6.8,
    autonomousLevel: 'L2'
  },
  {
    id: 'tank_500',
    brand: Brand.TANK,
    name: '坦克 500 Hi4-T',
    priceRange: [33.50, 33.50],
    range: 790,
    sales: 4000,
    type: CarType.OFFROAD,
    power: PowerType.PHEV,
    features: ['硬派越野', '豪华内饰', '纵置混动'],
    imageUrl: getPlaceHolder('Tank 500'),
    acceleration: 6.9,
    autonomousLevel: 'L2'
  },
  {
    id: 'wey_lanshan',
    brand: Brand.WEY,
    name: '魏牌 蓝山',
    priceRange: [29.98, 32.68],
    range: 1300,
    sales: 5500,
    type: CarType.SUV,
    power: PowerType.PHEV,
    features: ['大六座', '城市NOA', '冰箱彩电'],
    imageUrl: getPlaceHolder('Wey Lanshan'),
    acceleration: 4.9,
    autonomousLevel: 'City NOA'
  },
  {
    id: 'wey_gaoshan',
    brand: Brand.WEY,
    name: '魏牌 高山',
    priceRange: [33.58, 40.58],
    range: 1200,
    sales: 1200,
    type: CarType.MPV,
    power: PowerType.PHEV,
    features: ['行政MPV', '超长滑轨', '豪华舒适'],
    imageUrl: getPlaceHolder('Wey Gaoshan'),
    acceleration: 5.7,
    autonomousLevel: 'L2+'
  },
  {
    id: 'ora_goodcat',
    brand: Brand.ORA,
    name: '欧拉好猫',
    priceRange: [10.58, 13.58],
    range: 501,
    sales: 4500,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['复古造型', '女性喜爱', '精致小车'],
    imageUrl: getPlaceHolder('Ora Good Cat'),
    acceleration: 8.9,
    autonomousLevel: 'L2'
  },
  {
    id: 'ora_lightning',
    brand: Brand.ORA,
    name: '欧拉闪电猫',
    priceRange: [15.98, 24.13],
    range: 705,
    sales: 800,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['超流线造型', '运动轿跑', '复古豪华'],
    imageUrl: getPlaceHolder('Ora Lightning Cat'),
    acceleration: 4.3,
    autonomousLevel: 'L2'
  },
  {
    id: 'haval_raptor',
    brand: Brand.HAVAL,
    name: '哈弗 猛龙',
    priceRange: [16.58, 19.28],
    range: 1000,
    sales: 5000,
    type: CarType.SUV,
    power: PowerType.PHEV,
    features: ['方盒子', 'Hi4电四驱', '可城可野'],
    imageUrl: getPlaceHolder('Haval Raptor'),
    acceleration: 6.0,
    autonomousLevel: 'L2'
  },
  {
    id: 'haval_xiaolong_max',
    brand: Brand.HAVAL,
    name: '哈弗 枭龙MAX',
    priceRange: [15.98, 17.98],
    range: 1000,
    sales: 2500,
    type: CarType.SUV,
    power: PowerType.PHEV,
    features: ['全系电四驱', '中型SUV', '大空间'],
    imageUrl: getPlaceHolder('Xiaolong MAX'),
    acceleration: 6.8,
    autonomousLevel: 'L2'
  },

  // --- SAIC (MG, ROEWE, RISING) ---
  {
    id: 'mg4_ev',
    brand: Brand.MG,
    name: 'MG4 EV',
    priceRange: [11.58, 14.58],
    range: 520,
    sales: 4000,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['欧洲销冠', '后驱钢炮', '极致操控'],
    imageUrl: getPlaceHolder('MG4 EV'),
    acceleration: 3.8,
    autonomousLevel: 'L2'
  },
  {
    id: 'mg_cyberster',
    brand: Brand.MG,
    name: 'MG Cyberster',
    priceRange: [31.98, 36.58],
    range: 580,
    sales: 300,
    type: CarType.COUPE,
    power: PowerType.BEV,
    features: ['剪刀门', '软顶敞篷', '纯电跑车'],
    imageUrl: getPlaceHolder('MG Cyberster'),
    acceleration: 3.2,
    autonomousLevel: 'L2'
  },
  {
    id: 'roewe_d7',
    brand: Brand.ROEWE,
    name: '荣威 D7 DMH',
    priceRange: [10.98, 13.28],
    range: 1400,
    sales: 6500,
    type: CarType.SEDAN,
    power: PowerType.PHEV,
    features: ['超长续航', 'B级尺寸', '高性价比'],
    imageUrl: getPlaceHolder('Roewe D7'),
    acceleration: 7.9,
    autonomousLevel: 'L2'
  },
  {
    id: 'rising_r7',
    brand: Brand.RISING,
    name: '飞凡 R7',
    priceRange: [18.99, 22.99],
    range: 670,
    sales: 1000,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['换电', '湾流座椅', '大屏座舱'],
    imageUrl: getPlaceHolder('Rising R7'),
    acceleration: 5.8,
    autonomousLevel: 'L2+'
  },
  {
    id: 'rising_f7',
    brand: Brand.RISING,
    name: '飞凡 F7',
    priceRange: [18.99, 30.99],
    range: 702,
    sales: 800,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['巴赫座舱', '舒适大沙发', '换电'],
    imageUrl: getPlaceHolder('Rising F7'),
    acceleration: 3.7,
    autonomousLevel: 'L2+'
  },

  // --- DONGFENG (VOYAH, NAMMI, EPI) ---
  {
    id: 'voyah_free',
    brand: Brand.VOYAH,
    name: '岚图 FREE',
    priceRange: [22.89, 22.89],
    range: 1201,
    sales: 2000,
    type: CarType.SUV,
    power: PowerType.REEV,
    features: ['百度阿波罗智驾', '升降仪表台', '驾控优秀'],
    imageUrl: getPlaceHolder('Voyah FREE'),
    acceleration: 4.8,
    autonomousLevel: 'High-Speed NOA'
  },
  {
    id: 'voyah_dreamer',
    brand: Brand.VOYAH,
    name: '岚图 梦想家',
    priceRange: [33.99, 46.99],
    range: 1231,
    sales: 4500,
    type: CarType.MPV,
    power: PowerType.PHEV,
    features: ['华为乾昆智驾', '豪华底盘', '安全堡垒'],
    imageUrl: getPlaceHolder('Voyah Dreamer'),
    acceleration: 5.9,
    autonomousLevel: 'City NOA'
  },
   {
    id: 'voyah_zhiyin',
    brand: Brand.VOYAH,
    name: '岚图 知音',
    priceRange: [17.99, 23.69],
    range: 901,
    sales: 3000,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['超长续航', '800V', '全球车型'],
    imageUrl: getPlaceHolder('Voyah Zhiyin'),
    acceleration: 6.8,
    autonomousLevel: 'L2+'
  },
  {
    id: 'nammi_01',
    brand: Brand.NAMMI,
    name: '东风纳米 01',
    priceRange: [7.48, 10.68],
    range: 430,
    sales: 4000,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['无框车门', '大空间', '精致代步'],
    imageUrl: getPlaceHolder('Nammi 01'),
    acceleration: 12.0,
    autonomousLevel: 'L2'
  },
  {
    id: 'epi_007',
    brand: Brand.EPI,
    name: '东风奕派 eπ007',
    priceRange: [13.16, 19.66],
    range: 1200,
    sales: 3500,
    type: CarType.SEDAN,
    power: PowerType.REEV,
    features: ['剪刀门', '翻转仪表', '高性价比'],
    imageUrl: getPlaceHolder('ePi 007'),
    acceleration: 3.9,
    autonomousLevel: 'L2+'
  },
  {
    id: 'epi_008',
    brand: Brand.EPI,
    name: '东风奕派 eπ008',
    priceRange: [20.66, 21.16],
    range: 1300,
    sales: 4000,
    type: CarType.SUV,
    power: PowerType.REEV,
    features: ['六座布局', '冰箱彩电', '家庭用车'],
    imageUrl: getPlaceHolder('ePi 008'),
    acceleration: 6.8,
    autonomousLevel: 'L2'
  },

  // --- OTHERS (CHERY, HONGQI, WULING, ETC) ---
  {
    id: 'wuling_miniev',
    brand: Brand.WULING,
    name: '宏光 MINI EV',
    priceRange: [3.28, 9.99],
    range: 215,
    sales: 25000,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['国民神车', '极致小巧', '改装潜力'],
    imageUrl: getPlaceHolder('Mini EV'),
    acceleration: 15.0,
    autonomousLevel: 'L2'
  },
  {
    id: 'wuling_bingo',
    brand: Brand.WULING,
    name: '五菱 缤果',
    priceRange: [5.68, 8.88],
    range: 410,
    sales: 22000,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['复古可爱', '大空间', '代步升级'],
    imageUrl: getPlaceHolder('Wuling Bingo'),
    acceleration: 12.0,
    autonomousLevel: 'L2'
  },
   {
    id: 'wuling_starlight',
    brand: Brand.WULING,
    name: '五菱 星光',
    priceRange: [7.98, 10.98],
    range: 1100,
    sales: 8500,
    type: CarType.SEDAN,
    power: PowerType.PHEV,
    features: ['超低油耗', 'B级尺寸', 'A级价格'],
    imageUrl: getPlaceHolder('Wuling Starlight'),
    acceleration: 7.9,
    autonomousLevel: 'L2'
  },
  {
    id: 'icar_03',
    brand: Brand.ICAR,
    name: 'iCAR 03',
    priceRange: [10.98, 16.98],
    range: 501,
    sales: 5000,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['全铝车身', '方盒子', '大疆智驾'],
    imageUrl: getPlaceHolder('iCAR 03'),
    acceleration: 6.5,
    autonomousLevel: 'High-Speed NOA'
  },
  {
    id: 'icar_v23',
    brand: Brand.ICAR,
    name: 'iCAR V23',
    priceRange: [11.00, 15.00],
    range: 500,
    sales: 3000,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['复古越野', '致敬经典', '个性潮玩'],
    imageUrl: getPlaceHolder('iCAR V23'),
    acceleration: 7.0,
    autonomousLevel: 'L2'
  },
  {
    id: 'chery_fulwin_t9',
    brand: Brand.FULWIN,
    name: '奇瑞风云 T9',
    priceRange: [12.99, 16.99],
    range: 1400,
    sales: 8500,
    type: CarType.SUV,
    power: PowerType.PHEV,
    features: ['豪华七座', '鲲鹏超能混动', '高安全'],
    imageUrl: getPlaceHolder('Fulwin T9'),
    acceleration: 7.0,
    autonomousLevel: 'L2'
  },
  {
    id: 'chery_fulwin_a8',
    brand: Brand.FULWIN,
    name: '奇瑞风云 A8',
    priceRange: [10.99, 14.99],
    range: 1400,
    sales: 3500,
    type: CarType.SEDAN,
    power: PowerType.PHEV,
    features: ['续航反向虚标', '高速不失速', '实测2000km'],
    imageUrl: getPlaceHolder('Fulwin A8'),
    acceleration: 7.0,
    autonomousLevel: 'L2'
  },
  {
    id: 'hongqi_eh7',
    brand: Brand.HONGQI,
    name: '红旗 EH7',
    priceRange: [22.98, 30.98],
    range: 820,
    sales: 1200,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['国车安全', '低温长续航', '大空间'],
    imageUrl: getPlaceHolder('Hongqi EH7'),
    acceleration: 3.5,
    autonomousLevel: 'L2+'
  },
   {
    id: 'arcfox_alpha_t5',
    brand: Brand.ARCFOX,
    name: '极狐 阿尔法T5',
    priceRange: [15.58, 19.98],
    range: 660,
    sales: 3500,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['800V超充', '健康座舱', '高性价比'],
    imageUrl: getPlaceHolder('Arcfox Alpha T5'),
    acceleration: 7.5,
    autonomousLevel: 'L2+'
  },
  {
    id: 'arcfox_kaola',
    brand: Brand.ARCFOX,
    name: '极狐 考拉',
    priceRange: [11.98, 16.98],
    range: 500,
    sales: 2000,
    type: CarType.MPV,
    power: PowerType.BEV,
    features: ['亲子神车', '侧滑门', '母婴级健康'],
    imageUrl: getPlaceHolder('Arcfox Kaola'),
    acceleration: 10.0,
    autonomousLevel: 'L2'
  },
   {
    id: 'baojun_yep',
    brand: Brand.BAOJUN,
    name: '宝骏 悦也',
    priceRange: [8.08, 9.08],
    range: 303,
    sales: 1500,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['个性潮玩', 'Car-watch', '硬派造型'],
    imageUrl: getPlaceHolder('Baojun Yep'),
    acceleration: 15.0,
    autonomousLevel: 'L2'
  },
  {
    id: 'baojun_yep_plus',
    brand: Brand.BAOJUN,
    name: '宝骏 悦也Plus',
    priceRange: [9.38, 10.38],
    range: 401,
    sales: 2000,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['五门版', '大疆智驾', '实用升级'],
    imageUrl: getPlaceHolder('Baojun Yep Plus'),
    acceleration: 12.0,
    autonomousLevel: 'High-Speed NOA'
  },
  {
    id: 'baojun_yunhai',
    brand: Brand.BAOJUN,
    name: '宝骏 云海',
    priceRange: [10.98, 13.38],
    range: 600,
    sales: 2500,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['全系标配智驾', '超长续航', '性价比'],
    imageUrl: getPlaceHolder('Baojun Yunhai'),
    acceleration: 7.8,
    autonomousLevel: 'High-Speed NOA'
  },
  {
    id: 'buick_e5',
    brand: Brand.BUICK,
    name: '别克 E5',
    priceRange: [15.99, 22.99],
    range: 620,
    sales: 3000,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['奥特能平台', '合资大厂', '安全可靠'],
    imageUrl: getPlaceHolder('Buick E5'),
    acceleration: 7.6,
    autonomousLevel: 'L2'
  },
  {
    id: 'buick_gl8_phev',
    brand: Brand.BUICK,
    name: '别克 GL8 陆尊 PHEV',
    priceRange: [35.99, 41.99],
    range: 1370,
    sales: 4500,
    type: CarType.MPV,
    power: PowerType.PHEV,
    features: ['MPV王者', '插混升级', '商务首选'],
    imageUrl: getPlaceHolder('Buick GL8 PHEV'),
    acceleration: 7.8,
    autonomousLevel: 'L2'
  },
  {
    id: 'cadillac_lyriq',
    brand: Brand.CADILLAC,
    name: '凯迪拉克 锐歌',
    priceRange: [29.77, 41.97],
    range: 653,
    sales: 500,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['豪华纯电', '9K大屏', 'Super Cruise'],
    imageUrl: getPlaceHolder('Cadillac LYRIQ'),
    acceleration: 4.9,
    autonomousLevel: 'High-Speed NOA'
  },

  // --- TRADITIONAL LUXURY (BBA) ---
  {
    id: 'bmw_i3',
    brand: Brand.BMW,
    name: '宝马 i3',
    priceRange: [35.39, 41.39],
    range: 526,
    sales: 4000,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['3系操控', '空气悬架', '中国特供'],
    imageUrl: getPlaceHolder('BMW i3'),
    acceleration: 6.2,
    autonomousLevel: 'L2'
  },
  {
    id: 'bmw_ix3',
    brand: Brand.BMW,
    name: '宝马 iX3',
    priceRange: [40.50, 44.50],
    range: 530,
    sales: 2500,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['X3底盘', '高素质油改电', '好开'],
    imageUrl: getPlaceHolder('BMW iX3'),
    acceleration: 6.8,
    autonomousLevel: 'L2'
  },
  {
    id: 'bmw_i4',
    brand: Brand.BMW,
    name: '宝马 i4',
    priceRange: [42.99, 46.99],
    range: 625,
    sales: 800,
    type: CarType.COUPE,
    power: PowerType.BEV,
    features: ['进口轿跑', 'M运动底盘', '极致驾驶'],
    imageUrl: getPlaceHolder('BMW i4'),
    acceleration: 5.7,
    autonomousLevel: 'L2'
  },
  {
    id: 'bmw_i7',
    brand: Brand.BMW,
    name: '宝马 i7',
    priceRange: [94.90, 145.90],
    range: 650,
    sales: 200,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['行政旗舰', '后排巨幕', '水晶内饰'],
    imageUrl: getPlaceHolder('BMW i7'),
    acceleration: 4.7,
    autonomousLevel: 'L2+'
  },
  {
    id: 'benz_eqe',
    brand: Brand.BENZ,
    name: '奔驰 EQE',
    priceRange: [47.80, 53.43],
    range: 717,
    sales: 1500,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['弓形车身', '豪华氛围', '超长续航'],
    imageUrl: getPlaceHolder('Benz EQE'),
    acceleration: 6.7,
    autonomousLevel: 'L2'
  },
  {
    id: 'benz_eqe_suv',
    brand: Brand.BENZ,
    name: '奔驰 EQE SUV',
    priceRange: [48.60, 63.06],
    range: 613,
    sales: 1200,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['豪华越野', 'Hyperscreen', '舒适静谧'],
    imageUrl: getPlaceHolder('Benz EQE SUV'),
    acceleration: 6.8,
    autonomousLevel: 'L2'
  },
  {
    id: 'benz_eqs',
    brand: Brand.BENZ,
    name: '奔驰 EQS',
    priceRange: [88.10, 133.90],
    range: 800,
    sales: 300,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['纯电S级', '风阻系数极低', '百万豪车'],
    imageUrl: getPlaceHolder('Benz EQS'),
    acceleration: 4.4,
    autonomousLevel: 'L2+'
  },
  {
    id: 'vw_id3',
    brand: Brand.VW,
    name: '大众 ID.3',
    priceRange: [12.58, 14.98],
    range: 450,
    sales: 12000,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['德系底盘', '后驱小钢炮', '极佳操控'],
    imageUrl: getPlaceHolder('VW ID.3'),
    acceleration: 8.0,
    autonomousLevel: 'L2'
  },
  {
    id: 'vw_id4_crozz',
    brand: Brand.VW,
    name: '大众 ID.4 CROZZ',
    priceRange: [19.39, 29.39],
    range: 600,
    sales: 4500,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['德系SUV', 'MEB平台', '安全可靠'],
    imageUrl: getPlaceHolder('VW ID.4'),
    acceleration: 8.5,
    autonomousLevel: 'L2'
  },
  {
    id: 'vw_id6_crozz',
    brand: Brand.VW,
    name: '大众 ID.6 CROZZ',
    priceRange: [25.89, 33.69],
    range: 560,
    sales: 2000,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['六/七座布局', '家庭实用', '空间灵活'],
    imageUrl: getPlaceHolder('VW ID.6'),
    acceleration: 9.1,
    autonomousLevel: 'L2'
  },
  {
    id: 'vw_id7',
    brand: Brand.VW,
    name: '大众 ID.7 VIZZION',
    priceRange: [22.77, 26.27],
    range: 642,
    sales: 1500,
    type: CarType.SEDAN,
    power: PowerType.BEV,
    features: ['电动迈腾', '掀背尾门', '智能变色天幕'],
    imageUrl: getPlaceHolder('VW ID.7'),
    acceleration: 5.2,
    autonomousLevel: 'L2+'
  },
  {
    id: 'audi_q4',
    brand: Brand.AUDI,
    name: '奥迪 Q4 e-tron',
    priceRange: [28.99, 36.71],
    range: 605,
    sales: 2000,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['MEB平台', '奥迪虚拟座舱', '紧凑豪华'],
    imageUrl: getPlaceHolder('Audi Q4 e-tron'),
    acceleration: 8.8,
    autonomousLevel: 'L2'
  },
  {
    id: 'audi_q5_etron',
    brand: Brand.AUDI,
    name: '奥迪 Q5 e-tron',
    priceRange: [29.85, 41.55],
    range: 560,
    sales: 1500,
    type: CarType.SUV,
    power: PowerType.BEV,
    features: ['中国特供', '六/七座', '家用豪华'],
    imageUrl: getPlaceHolder('Audi Q5 e-tron'),
    acceleration: 9.3,
    autonomousLevel: 'L2'
  }
];

export const SYSTEM_INSTRUCTION = `
你是一个专业、客观且热情的中国新能源汽车智能选车助手。
你的任务是根据用户的需求（预算、车型、用途、偏好等）进行分析，并从数据库中推荐最合适的3款车型。

**你的回答必须严格遵循以下 JSON 格式**，不要包含 markdown 格式标记（如 \`\`\`json），直接返回纯 JSON 字符串：

{
  "analysis": "一段简短的分析，说明为什么推荐这几款车，结合用户的预算和需求。（100字以内）",
  "recommendations": [
    {
      "id": "必须精准对应数据库中的车型ID (例如 'xiaomi_su7', 'li_l6')",
      "reason": "推荐理由，突出该车最符合用户哪一点需求（例如：您的预算范围内性能最强）。"
    },
    ... (共3个)
  ]
}

以下是车辆数据库供你检索：
${JSON.stringify(CAR_DATABASE.map(c => ({
    id: c.id,
    name: c.name,
    brand: c.brand,
    price: c.priceRange,
    range: c.range,
    power: c.power,
    type: c.type,
    level: c.autonomousLevel,
    features: c.features
})))}

如果找不到完美的匹配，请推荐最接近的选项，并在 reason 中说明。
`;